name = "G"
uuid = "aad88905-9c29-482c-9acd-2047d8c1a9cc"
authors = ["powerzf <18883350900@163.com> and contributors"]
version = "0.1.0"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
julia = "1"

[targets]
test = ["Test"]
